# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e3e4b35572e564184dc2fa92bb1e56322afcb0b395f8cda94f60ad004bd2d01d9970a19e2c2689ce33f15ddfa5da94bfe55e6df686baabb2067acba03a64479

test:
  secret_key_base: 4415ae2c54fc9f8a7b39c1f7630761ad5c7099cd1242a83923f83fd3e02b4aa3490f941d0f0ae15cca44c0f684ebad2e3eb60c33ca8d89d2ff840865a4348dd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
